feat: Maxcompute sink second phase
goto/depot pull request #57
Opened 2024-12-10 07:36 UTC by ekawinataa

2024-12-11 04:59 UTC, mayankrai09 commented on src/main/java/com/gotocompany/depot/metrics/MaxComputeMetrics.java
> +    public String getMaxComputeConversionLatencyMetric() {
Can we also add metrics to track the number of upload sessions created by firehose?

2024-12-16 05:42 UTC, ekawinataa commented on src/main/java/com/gotocompany/depot/maxcompute/converter/MessageProtobufMaxComputeConverter.java
> +        protoPayload.getFieldDescriptor().getMessageType().getFields().forEach(innerFieldDescriptor -> {
revert

2024-12-16 05:42 UTC, ekawinataa commented on src/main/java/com/gotocompany/depot/maxcompute/converter/ProtobufMaxComputeConverter.java
> +    default TypeInfo wrapTypeInfo(Descriptors.FieldDescriptor fieldDescriptor, TypeInfo typeInfo) {
simplify

2024-12-19 11:34 UTC, ekawinataa commented on src/main/java/com/gotocompany/depot/maxcompute/MaxComputeSinkFactory.java
> +                new Instrumentation(statsDReporter, RecordDecorator.class),
pass the StatsDReporter and let the concerned class instantiate the instrumentation

2024-12-19 11:34 UTC, ekawinataa commented on src/main/java/com/gotocompany/depot/maxcompute/MaxComputeSinkFactory.java
>                  new Instrumentation(statsDReporter, MaxComputeSink.class), maxComputeMetrics);
pass the StatsDReporter and let the concerned class instantiate the instrumentation

2024-12-19 11:37 UTC, ekawinataa commented on src/main/java/com/gotocompany/depot/maxcompute/client/insert/InsertManagerFactory.java
> +        StreamingSessionManager streamingSessionManager = getStreamingSessionManager(maxComputeSinkConfig, tableTunnel, instrumentation, maxComputeMetrics);
revert to ternary

2024-12-19 11:40 UTC, ekawinataa commented on src/main/java/com/gotocompany/depot/maxcompute/client/insert/InsertManagerFactory.java
> +        StreamingSessionManager streamingSessionManager = getStreamingSessionManager(maxComputeSinkConfig, tableTunnel, instrumentation, maxComputeMetrics);
Declare it directly under the insert manager

2024-12-19 13:10 UTC, rajuGT requested changes

2024-12-19 15:07 UTC, rajuGT approved these changes

2024-12-20 05:03 UTC, mayankrai09 commented on docs/reference/configuration/generic.md
> +Enable instrumentation for unknown fields validation. Instrumentation itself will introduces some overhead, so it should be enabled when needed.
Enable instrumentation for unknown field validation for individual records. The instrumentation will introduce some overhead, So it should be enabled when needed.

2024-12-20 05:24 UTC, mayankrai09 approved these changes

2024-12-20 05:26 UTC, merged